// <auto-generated />
using Ketchup.Zero.Application;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ketchup.Zero.Application.Migrations
{
    [DbContext(typeof(ZeroDbContext))]
    partial class ZeroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ketchup.Zero.Application.Domain.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<sbyte>("Level")
                        .HasColumnType("tinyint(4)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Operates")
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Sort")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("sys_menu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Level = (sbyte)1,
                            Name = "基础数据管理",
                            Operates = "[]",
                            ParentId = 0,
                            Sort = 0,
                            Url = "/"
                        },
                        new
                        {
                            Id = 2,
                            Level = (sbyte)2,
                            Name = "按钮管理",
                            Operates = "[1,2,3,4]",
                            ParentId = 1,
                            Sort = 1,
                            Url = "operate"
                        },
                        new
                        {
                            Id = 3,
                            Level = (sbyte)2,
                            Name = "角色管理",
                            Operates = "[1,2,3,4]",
                            ParentId = 1,
                            Sort = 2,
                            Url = "role"
                        },
                        new
                        {
                            Id = 4,
                            Level = (sbyte)2,
                            Name = "菜单管理",
                            Operates = "[1,2,3,4]",
                            ParentId = 1,
                            Sort = 3,
                            Url = "menu"
                        },
                        new
                        {
                            Id = 5,
                            Level = (sbyte)2,
                            Name = "系统用户",
                            Operates = "[1,2,3,4]",
                            ParentId = 1,
                            Sort = 4,
                            Url = "sysUser"
                        });
                });

            modelBuilder.Entity("Ketchup.Zero.Application.Domain.SysOperate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasMaxLength(2147483647);

                    b.Property<int>("Unique")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("sys_operate");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "添加",
                            Unique = 1001
                        },
                        new
                        {
                            Id = 2,
                            Name = "编辑",
                            Unique = 1002
                        },
                        new
                        {
                            Id = 3,
                            Name = "查询",
                            Unique = 1003
                        },
                        new
                        {
                            Id = 4,
                            Name = "删除",
                            Unique = 1004
                        });
                });

            modelBuilder.Entity("Ketchup.Zero.Application.Domain.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Remark")
                        .HasColumnType("longtext CHARACTER SET utf8mb4")
                        .HasMaxLength(2147483647);

                    b.HasKey("Id");

                    b.ToTable("sys_role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "管理员"
                        });
                });

            modelBuilder.Entity("Ketchup.Zero.Application.Domain.SysRoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("Operates")
                        .HasColumnType("varchar(200) CHARACTER SET utf8mb4")
                        .HasMaxLength(200);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("sys_roleMenu");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MenuId = 1,
                            Operates = "[]",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            MenuId = 2,
                            Operates = "[1,2,3,4]",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3,
                            MenuId = 3,
                            Operates = "[1,2,3]",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4,
                            MenuId = 4,
                            Operates = "[1,2,3,4]",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Ketchup.Zero.Application.Domain.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(500) CHARACTER SET utf8mb4")
                        .HasMaxLength(500);

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(32) CHARACTER SET utf8mb4")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.ToTable("sys_user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "46F94C8DE14FB36680850768FF1B7F2A",
                            RoleId = 1,
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
